#ifndef COMMON_H
#define COMMON_H

typedef enum {
    SUCCESS = 0,
    DEVICE_NOT_FOUND = 1,
    ADD_PARTITION_FAILED = 2,
    COMMIT_PARTITION_FAILED = 3,
    WRITE_FAILED = 4,
    OPEN_DEVICE_FAILED = 5,
    FILE_SYNC_FAILED = 6,
    MOUNT_POINT_FOUND = 7,
    MOUNT_POINT_NOT_FOUND = 8,
    GET_MOUNT_ERROR = 9,
    UNMOUNT_DEVICE_SUCCESS = 10,
    UNMOUNT_DEVICE_FAILED =  11,
    NO_PERMIT_OPERATION = 12,
    LOAD_DISK_INFO_FAILED = 13,
    PARTITION_NOT_FOUND = 14,
    GET_GEOMETRY_PARTITION_FAILED = 15,
    PARTITION_TO_SMALL = 16,
    PARTITION_TO_BIG = 17,
    WRITE_BOOT_SECTOR_FAILED = 18,
    MAX_CLUSTER_ERROR = 19,
    WRITE_FS_INFO_FAILED = 20,
    WRITE_FAT_FAILED = 21,
    WRITE_ROOT_DIR_FAILED = 22,
    FORMAT_FAT32_FAILED = 23
} RESULT_STATUS;

#endif // COMMON_H